import FWCore.ParameterSet.Config as cms

l1Analyzer = cms.EDAnalyzer("L1Analyzer",
    ecalDigis = cms.InputTag("ecalDigis","EcalTriggerPrimitives"),
    hcalDigis = cms.InputTag("hcalDigis"),
    stage2Layer1Digis = cms.InputTag("stage2Layer1Digis"),
    stage2EG = cms.InputTag("caloStage2Digis","EG"),
    stage2Tau = cms.InputTag("caloStage2Digis","Tau"),
    stage2Jet = cms.InputTag("caloStage2Digis","Jet"),
    stage2Muon = cms.InputTag("caloStage2Digis","Muon"),
    stage2EtSum = cms.InputTag("caloStage2Digis","EtSum"),
    electrons = cms.InputTag("slimmedElectrons"),
    photons = cms.InputTag("slimmedPhotons"),
    jets = cms.InputTag("slimmedJets"),
    met = cms.InputTag("slimmedMETs"),
    electronIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Summer16-80X-V1-loose"),
    electronPairs = cms.InputTag("TODO"),
    genParticles = cms.InputTag("genParticles"),
    storeEcal = cms.bool(True),
    storeHcal = cms.bool(True),
    storeStage2Layer1 = cms.bool(True),
    storeStage2 = cms.bool(True),
    LSB = cms.double(0.5),
    isMC = cms.bool(False),
)
